# This file was generated by GoReleaser. DO NOT EDIT.
cask "afauth" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8904762eb3d6ec50d6256fe518d4bee250520703b454ec2755633c7e64daf2cf"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce64169f39b1624ee518f30f91429c454bcffdeef383925095db58cca063c02e"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f30b885c20362a50663ca6c74017cbb89389e1e19d313668c782ad7c09b1c08"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "048d5619e5f3800261a3cf097f7ab21effa87193ae18730acc3557955c7c834a"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_linux_arm64.tar.gz"
    end
  end

  name "afauth"
  desc "Agent-First Auth — reference CLI"
  homepage "https://afauth.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afauth"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afauth"]
    end
  end

  # No zap stanza required

end
