# This file was generated by GoReleaser. DO NOT EDIT.
cask "afauth" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "2f760bb1384e23f72808a6552e6a6f46d932cfc02f3e46166fa8b070f620f241"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3103fc3695d0f1f3010eee734feedac92bf7ce15d035e68fe902a242bc02da65"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e9b79ee0e066f668508a4d82b22c305c544e376f313865946f68190f4577385"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "06475c79b54cec203edf8cb88bea9c549abf1d3aa90cd7df8fa09c16dcf58c09"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_linux_arm64.tar.gz"
    end
  end

  name "afauth"
  desc "Agent-First Auth — reference CLI"
  homepage "https://afauth.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afauth"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afauth"]
    end
  end

  # No zap stanza required

end
