# This file was generated by GoReleaser. DO NOT EDIT.
cask "afauth" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "44ba1a09d6bdf893f9f43973ccffe373272323952cd72c8736b34b7d57c23ebf"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3c3f0508a9a8c15c6265b1198cc77ba1101801c31deb2340613be3fe85e4dce"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f9204622e2a80734f9b07c6be37837e03ecfaeec68f0f7e266a6339720fb9ba7"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ab66af8b30a6920247d824d1ad9f80b5480e16a943c11df93f818dd90d4c00e"
      url "https://github.com/AFAuthHQ/cli/releases/download/v#{version}/afauth_#{version}_linux_arm64.tar.gz"
    end
  end

  name "afauth"
  desc "Agent-First Auth — reference CLI"
  homepage "https://afauth.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afauth"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afauth"]
    end
  end

  # No zap stanza required

end
